name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
      - "!main"
    paths-ignore:
      - "**/.md"

env:
  REGISTRY_IMAGE: ghcr.io/medxops/trazr-gen

jobs:
  build:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build only
        run: |
          # Ensure binary is in root for Docker build
          if [ -f ./build/trazr-gen ]; then
            cp ./build/trazr-gen ./trazr-gen
          elif [ ! -f ./trazr-gen ]; then
            echo "Binary not found in ./build or root!" && exit 1
          fi
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ env.REGISTRY_IMAGE }}:${{ github.sha }} \
            .
